services:
  db:
    build: containers/mysql
    env_file:
      - ./environments/common.env
      - ./environments/db.env
    volumes:
      - ../volumes/db/data:/var/lib/mysql
    ports:
      - 3306:3306
      
  app:
    build: containers/spring
    env_file:
      - ./environments/common.env
      - ./environments/db.env
    command: ./mvnw clean spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005"
    volumes:
      - ../volumes/app:/app
      - ../volumes/app/.m2:/root/.m2
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - db
      
  web:
    build: containers/nginx
    env_file:
      - ./environments/common.env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
