# 接続先はDocker Composeのサービス名です。
spring.datasource.url=jdbc:mysql://db:3306/demo-db?serverTimezone=JST
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Web公開設定（Docker必須）
server.port=8080
server.address=0.0.0.0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.session.tracking-modes=cookie
# H2 Consoleを有効にする
spring.h2.console.enabled=true
# アクセスURLを /h2-console に設定（デフォルトですが明記しておくと安心）
spring.h2.console.path=/h2-console
